<a href="https://colab.research.google.com/github/marcekovam/Data_science_practicum_2025/blob/main/Lesson1_A_Short_Intro_To_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Short Introduction To Python

This introduction is recommended for coders coming from other language (e.g. `R`). I expect you to already know concept like a lists, conditional statements, loops or functions.   

There is a plenty of material online to get oriented in Python. For example, skim Learn Python in ... minutes
https://learnxinyminutes.com/docs/python/ and try do do the exercises below. If you stack, ask for help (do not waste time). There are no wrong questions. Please, work in pairs - only the person with less experience is allowed to touch the keyboard.

To start with, please, copy this notebook into your GDrive (from menu select File -> Save a copy in drive).



## Python Basic

1) Save a number 3 into a variable `a` and print it

*Expected output:*

3

In [1]:
a = 3
print(a)

3


2) Take the radius of a circle in a variable `r` and calculate the area:

*Input:*

`r = 1.2`

*Output:*

`Area = 4.523893421169302`

In [4]:
import math
r = 1.2

# YOUR CODE
area = math.pi*r**2
print(f'Area: {area:.2f}')


Area: 4.52


3) Simulate throwing a dice (return a random number between 1 and 6).

In [14]:
import random

random_number = random.randint(1, 6)
print(random_number)

2


## Strings

1) Write a Python program to calculate the length of a string.

*Input:*

`s = 'OMG!`

*Output:*

4

In [15]:
s = 'OMG!'
print(len(s))

4


3) Write a Python program to get a single string from two given strings, separated by a space and swap the first two characters of each string.

*Sample Strings* : 'abc', 'xyz'

*Expected Result* : 'xyc abz'

In [19]:
s1 = 'abc'
s2 = 'xyz'

# YOUR CODE
s = s2[0:2] + s1[2:] + ' ' + s1[0:2] + s2[2:]
print(s)

xyc abz


3) Write a Python program to count the number of characters (character frequency) in a string. (hint: try Counter from collections module)

*Input* : 'google.com'

*Output* : {'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}

In [21]:
from collections import Counter

s = 'google.com'
char_count = Counter(s)
print(char_count)

Counter({'o': 3, 'g': 2, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1})


# Lists

1) Write a Python program to get the smallest, the largest number from a list and a sum of a list.

*Input:* [3, 8, 1, 9]

*Output:* 1, 9, 21

In [22]:
nums = [3, 8, 1, 9]
print(min(nums), max(nums), sum(nums))

1 9 21


2) Write a Python program to print a list from 2nd to 3rd element and the last element.

*Sample List:* ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']

*Expected Output:* ['Green', 'White', 'Yellow']

In [25]:
items = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
print(items[1:3] + items[-1:])

['Green', 'White', 'Yellow']


3) Write a Python program to print a every second element of a list in a reverse order.

*Input:* [8, 4, 3, 6, 7]

*Output: [7, 3, 8]*

In [26]:
a = [8, 4, 3, 6, 7]
a[::-2]

[7, 3, 8]

4) Write a Python program to print the numbers of a specified list after removing even numbers from it. (hint: search for list comprehensions)

*Input*: [8, 4, 3, 5, 7]

*Output*: [3, 5, 7]

In [27]:
a = [8, 4, 3, 5, 7]
b = [item for item in a if item % 2 == 1]
print(*b)

3 5 7


## Dictionary

1) Write a Python script to add a key to a dictionary.

*Sample Dictionary:* `{0: 10, 1: 20}`

*Expected Result:* `{0: 10, 1: 20, 2: 30}`

In [30]:
dictionary = {0: 10, 1: 20}
dictionary[2] = 30
print(dictionary)

{0: 10, 1: 20, 2: 30}


2) Write a Python script to check whether a given key `"default"` already exists in a dictionary.

*Sample Dictionary*: `d = {'default': 0, 'extra': 1}`

*Expected Output*: True

In [31]:
d = {'default': 0, 'extra': 1}
print('default' in d)

True


3) Write a Python script to generate and print a dictionary that contains a number (between 1 and n) in the form `(x, x*x)`. (*hint*: to generate through numbers 1..N, use `range(1, N+1)`)

*Sample Dictionary*: (n = 5)

*Expected Output*: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [33]:
n = 5
dictionary = {i: i**2 for i in range(1, n + 1)}
print(dictionary)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


## Conditional statements and loops

1) Write a Python program to construct the following pattern, using a loop.

```
* * * * *
* * * *
* * *
* *
*
```

In [35]:
for i in range(0, 5):
  print('* '*(5 - i))

* * * * * 
* * * * 
* * * 
* * 
* 


2) Write a Python program to count the number of even and odd numbers from a series of numbers.

*Sample numbers*: numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

*Expected Output*:

Number of even numbers : 4

Number of odd numbers : 5

In [36]:
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
even = len([n for n in numbers if n % 2 == 0])
odd = len([n for n in numbers if n % 2 == 1])
print(f'Number of even numbers: {even}')
print(f'Number of odd numbers: {odd}')

Number of even numbers: 4
Number of odd numbers: 5


3) Write a Python program which iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

*Sample Output*:
```
fizzbuzz
1
2
fizz
4
buzz
```

In [38]:
for i in range(1, 21):
  if i % 3 == 0 and i % 5 == 0:
    print('fizzbuzz')
  elif i % 3 == 0:
    print('fizz')
  elif i % 5 == 0:
    print('buzz')
  else:
    print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz


4) Write a Python program which takes two digits m (row) and n (column) as input and generates a "two-dimensional" list. The element value in the i-th row and j-th column of the array should be i*j.

*Test Data*: Rows = 3, Columns = 4

*Expected Result*: [[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]

In [41]:
Rows = 3
Columns = 4
array = [[i*j for i in range(0, Columns)] for j in range(0, Rows)]
print(array)

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]


## Functions

1) Write a Python program to reverse a string.

*Sample String*: "1234abcd"

*Expected Output*: "dcba4321"

In [44]:
s = "1234abcd"

def reverse_string(x):
  # YOUR CODE
  s = x[::-1]
  return(s)

reverse_string(s)

'dcba4321'

2) Write a Python function to calculate the factorial of a number (a non-negative integer). The function accepts the number as an argument.

*Input:* 4

*Expected output:* 24

In [45]:
i = 4

def factorial(x):
  # YOUR CODE
  fact = 1
  while x > 1:
    fact *= x
    x -= 1
  return fact

factorial(i)

24

3) Write a Python function that takes a list and returns a new list with unique elements of the first list.

*Sample List*: [1,2,3,3,3,3,4,5]

*Unique List*: [1, 2, 3, 4, 5]

In [46]:
a = [1,2,3,3,3,3,4,5]

def unique_list(x):
  # YOUR CODE
  return list(set(x))

unique_list(a)

[1, 2, 3, 4, 5]

## Numpy Arrays

1)  Create a 1D array of numbers from 0 to 9

*Output:* `array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`



In [48]:
import numpy as np

array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


2) Find how to generate an array N x M of random numbers, zeroes, ones and how to get a shape (a dimension) of an array.

Generate an array 10x20 of random numbers between 0 and 1 anbd calculate a sum of each row.

In [52]:
array = np.random.rand(10, 20)
array_row_sum = np.sum(array, axis = 1)
print(array_row_sum)

[12.29859929  9.60389434 11.57427926  9.63909912 10.13984188  8.19273167
 11.80986926  9.26553026 11.79648864 11.39685707]


3) Replace all odd numbers in array with -1

*Input*: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

*Output*: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [53]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


4) Convert a 1D array to a 2D array with 2 rows

*Input*: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

*Output*: array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])

In [59]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2, -1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


5) Get the positions where elements of a and b match

*Input*:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

*Output*:

`array([1, 3, 5, 7])`

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

6)  Swap columns 1 and 2 in the array

*Input:*

```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

*Output:*

```
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
```

In [64]:
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]] = arr
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## Pandas

1) Read CSV file from http://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv into DataFrame `df`. Use 'country' as an index column. Print first 5 lines of `df`.

In [67]:
import pandas as pd

url = 'http://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv'
df = pd.read_csv(url, index_col = 'country')
df[:5]

year         pop continent  lifeExp   gdpPercap
country                                                     
Afghanistan  1952   8425333.0      Asia   28.801  779.445314
Afghanistan  1957   9240934.0      Asia   30.332  820.853030
Afghanistan  1962  10267083.0      Asia   31.997  853.100710
Afghanistan  1967  11537966.0      Asia   34.020  836.197138
Afghanistan  1972  13079460.0      Asia   36.088  739.981106

2) Print all information in the dataframe about "Czech Republic". Print only life expectancy progression in the Czech Republic (columns `year` and `lifeExp`).

In [69]:
df.loc['Czech Republic']
df.loc['Czech Republic', ['year', 'lifeExp']]

year  lifeExp
country                      
Czech Republic  1952   66.870
Czech Republic  1957   69.030
Czech Republic  1962   69.900
Czech Republic  1967   70.380
Czech Republic  1972   70.290
Czech Republic  1977   70.710
Czech Republic  1982   70.960
Czech Republic  1987   71.580
Czech Republic  1992   72.400
Czech Republic  1997   74.010
Czech Republic  2002   75.510
Czech Republic  2007   76.486

3) Print the value in the third row, second column.

*Expected output*: 31.997

In [78]:
df.iloc[2, 3]

np.float64(31.997)

4) Print all information from the year 2007.

In [80]:
df[df.year == 2007]

year         pop continent  lifeExp     gdpPercap
country                                                              
Afghanistan         2007  31889923.0      Asia   43.828    974.580338
Albania             2007   3600523.0    Europe   76.423   5937.029526
Algeria             2007  33333216.0    Africa   72.301   6223.367465
Angola              2007  12420476.0    Africa   42.731   4797.231267
Argentina           2007  40301927.0  Americas   75.320  12779.379640
...                  ...         ...       ...      ...           ...
Vietnam             2007  85262356.0      Asia   74.249   2441.576404
West Bank and Gaza  2007   4018332.0      Asia   73.422   3025.349798
Yemen Rep.          2007  22211743.0      Asia   62.698   2280.769906
Zambia              2007  11746035.0    Africa   42.384   1271.211593
Zimbabwe            2007  12311143.0    Africa   43.487    469.709298

[142 rows x 5 columns]

5) Find the country with the largest GDP per capita in 2007.

In [81]:
df[df.year == 2007].sort_values(by = 'gdpPercap', ascending = False).index[0]

'Norway'

6) In the year 2007, calculate the average life expectancy per continent (ignore a population size).

In [83]:
df[df.year == 2007].groupby('continent').mean()['lifeExp']

continent
Africa      54.806038
Americas    73.608120
Asia        70.728485
Europe      77.648600
Oceania     80.719500
Name: lifeExp, dtype: float64

## Acknowledgement

In preparation of this notebook, I have used and adapted materials from [W3 Python Tutorial Exercises](https://www.w3resource.com/python-exercises/), [101 NumPy Exercises for Data Analysis](https://www.machinelearningplus.com/python/101-numpy-exercises-python/) and [Software Carpentry workshop Python for Novices](https://ucsbcarpentry.github.io/2019-10-10-Python-UCSB/08-data-frames/).